from typing import Awaitable, List

MapTeamDict: dict # Dictionary of map and team name

async def bfban_checkBan(player_pid: str) -> Awaitable[str]: ...
async def bfeac_checkBanMulti(pids:list) -> Awaitable[dict]: ...
async def Blaze2788Pro(gameIds: List[int]) -> Awaitable[dict]: ...